SELECT X.ID_SOLICITUD,TIPOOP.ID_TIPO, TIPOOP.NOMBRE_TIPO AS NOMBRE_OPERACION, X.CANTIDAD_PRODUCTOS,  X.MONTO_OPERACION,   EMI.*, EMI.NOMBRE AS NOMBRE_EMISOR, VAL.*, TV.NOMBRE_VALOR AS TIPO_VALOR_V FROM
((((SELECT SOLICITUDES.*
FROM SOLICITUDOPERACION SOLICITUDES LEFT OUTER JOIN (REGISTROOPERACION REG INNER JOIN SOLICITUDOPERACION SOL ON SOL.ID_SOLICITUD=REG.FK_ID_SOLICITUD) ON SOL.ID_SOLICITUD = SOL.ID_SOLICITUD
WHERE SOL.ID_SOLICITUD IS NOT NULL)X INNER JOIN INVERSIONISTA INV ON X.FK_ID_INVERSIONISTA = INV.ID_INVERSIONISTA) INNER JOIN (VALOR VAL INNER JOIN TIPOVALOR TV ON VAL.FK_ID_TIPO_VALOR=TV.ID_TIPO_VALOR)ON X.FK_ID_VALOR=VAL.ID_VALOR) INNER JOIN EMISOR EMI ON VAL.FK_EMISOR=EMI.NIT)
INNER JOIN TIPOOPERACION TIPOOP ON X.FK_ID_TIPO=TIPOOP.ID_TIPO
WHERE INV.ID_INVERSIONISTA='INGRESADO';